export const LOGIN_ADMIN_REQUIEST = 'LOGIN_ADMIN_REQUIEST'
export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS'
export const LOGIN_ADMIN_FAIL = 'LOGIN_ADMIN_FAIL'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";