const clientslogo=[
    {
        id:1,
     
        img:"./clientslogo/1.png",
        alt:"logo1",
        title:"Hello",
        discription:"ffd"
    },
    {
        id:2,
        img:"./clientslogo/2.png",
        alt:"logo2",
        title:"Hello",
        discription:"ffd"
    },
    {
        id:3,
        img:"./clientslogo/3.png",
        alt:"logo3",
        title:"Hello",
        discription:"ffd"
    },
    {
        id:4,
        img:"./clientslogo/4.png",
        alt:"logo4",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:5,
        img:"./clientslogo/5.png",
        alt:"logo5",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:6,
        img:"./clientslogo/6.png",
        alt:"logo6",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:7,
        img:"./clientslogo/7.png",
        alt:"logo7",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:8,
        img:"./clientslogo/8.png",
        alt:"logo8",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:9,
        img:"./clientslogo/9.png",
        alt:"logo9",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:10,
        img:"./clientslogo/10.png",
        alt:"logo10",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:11,
        img:"./clientslogo/11.png",
        alt:"logo11",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:12,
        img:"./clientslogo/12.png",
        alt:"logo12",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:13,
        img:"./clientslogo/13.png",
        alt:"logo13",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:14,
        img:"./clientslogo/14.png",
        alt:"logo14",
        title:"Hello",
        discription:"ffd"
    },
    {
        id:15,
        img:"./clientslogo/15.png",
        alt:"logo15",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:16,
        img:"./clientslogo/16.png",
        alt:"logo16",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:17,
        img:"./clientslogo/17.png",
        alt:"logo17",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:18,
        img:"./clientslogo/49.png",
        alt:"logo18"
    },
    {
        id:19,
        img:"./clientslogo/19.png",
        alt:"logo19",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:20,
        img:"./clientslogo/20.png",
        alt:"logo20",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:21,
        img:"./clientslogo/21.png",
        alt:"logo21",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:22,
        img:"./clientslogo/23.png",
        alt:"logo23",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:24,
        img:"./clientslogo/24.png",
        alt:"logo24",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:25,
        img:"./clientslogo/25.png",
        alt:"logo25",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:26,
        img:"./clientslogo/26.png",
        alt:"logo26",
         title:"Hello",
        discription:"ffd"
    },
    
    {
        id:27,
        img:"./clientslogo/27.png",
        alt:"logo27",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:28,
        img:"./clientslogo/28.png",
        alt:"logo28",
        
    },
    {
        id:29,
        img:"./clientslogo/29.png",
        alt:"logo29",
        
    },
    {
        id:30,
        img:"./clientslogo/30.png",
        alt:"logo30",
        
    },
    {
        id:31,
        img:"./clientslogo/31.png",
        alt:"logo31",
        
    },
    {
        id:32,
        img:"./clientslogo/32.png",
        alt:"logo32",
        
    },
    {
        id:33,
        img:"./clientslogo/33.png",
        alt:"logo33",
        
    },
    {
        id:34,
        img:"./clientslogo/34.png",
        alt:"logo34",
        
    },
    {
        id:35,
        img:"./clientslogo/67.png",
        alt:"logo35",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:36,
        img:"./clientslogo/36.png",
        alt:"logo36",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:37,
        img:"./clientslogo/37.png",
        alt:"logo37",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:38,
        img:"./clientslogo/38.png",
        alt:"logo38",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:39,
        img:"./clientslogo/39.png",
        alt:"logo39",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:40,
        img:"./clientslogo/40.png",
        alt:"logo40",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:41,
        img:"./clientslogo/41.png",
        alt:"logo41",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:42,
        img:"./clientslogo/42.png",
        alt:"logo42"
    },
    {
        id:43,
        img:"./clientslogo/43.png",
        alt:"logo43"
    },
    {
        id:44,
        img:"./clientslogo/44.png",
        alt:"logo44"
    },
    {
        id:45,
        img:"./clientslogo/45.png",
        alt:"logo45",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:46,
        img:"./clientslogo/46.png",
        alt:"logo46",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:47,
        img:"./clientslogo/47.png",
        alt:"logo47",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:48,
        img:"./clientslogo/48.png",
        alt:"logo48",
         title:"Hello",
        discription:"ffd"
    },
    {
        id:49,
        img:"./clientslogo/50.png",
        alt:"logo26",
         title:"Hello",
        discription:"ffd"
    },
];

export default clientslogo;